apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-techjargon
  namespace: techjargon
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: techjargon.perfx.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: techjargon-service
            port: 
              number: 12909
  tls:
  - hosts:
    - techjargon.perfx.dev
    secretName: techjargon-ingress-cert 
