apiVersion: v1
kind: Service
metadata:
  name: techjargon-service
  namespace: techjargon
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /data/metrics
    prometheus.io/port: "12909"
spec:
  ports:
  - name: http
    port: 12909
    protocol: TCP
    targetPort: 12909
  selector:
    app: techjargon
  sessionAffinity: None

